### ISSUE TITLE
no highestPort ts definition in latest version

### ISSUE THREAD

**Issue by Hishengs** [http-party/node-portfinder#119]
hi, in the latest version: 1.0.28, there still no ts definition for **highestPort**

![image](https://user-images.githubusercontent.com/8407978/125884649-1ba85b97-dd29-4210-b40c-68613870313b.png)

![image](https://user-images.githubusercontent.com/8407978/125884662-a05855de-1d64-4cbe-adbe-2b5b4e6ba669.png)

**Comment by eriktrom** [comment]
add it and i'll merge.

in fact, if you do add it, consider adding something to the readme that says "contributions for ts defintions are actively merged, but due to the legacy requirements of this code base and the number of packages that depend on it,  enhancements in the form of typings are the only thing that are likely to get merged, unless there is a new operating system error we need to handle" (which is really the only thing I check issues for these days - however type definitions are a great way to gain more activity and build a larger community around this lib now that u bring it up.

:)

**Comment by eriktrom** [comment]
closing - will reopen if code submitted
